query GET_ALL_BANKS {
  getAllBanks {
    id
    name
    itno
    account
    active
    notes
  }
}

query BANK_BY_ID($id: ID!) {
  getBankById(id:$id) {
    id
    name
    itno
    account
    active
    notes
  }
}

query BANK_BY_LIMIT_PAGE($page: Int!, $limit: Int!, $search: String) {
  getBanksByLimitAndPage(
    page: $page,
    limit: $limit,
    search: $search
  ){
    banks{
      id
      name
      itno
      account
      active
      notes
    }
    paginator{
      currentPage,
      pageCount,
      prev,
      next,
      hasPrevPage
      hasNextPage
      perPage
      bankCount
    }
  }
}

mutation CREATE_NEW_BANK(
  $name: String! 
  $itno: String! 
  $account: String! 
  $active: Boolean 
  $notes: String
){
  createNewBank(
    newBank : {
      name: $name,
      itno: $itno,
      account: $account,
      active: $active,
      notes: $notes
    }
  ){
    id
    name
    itno
    account
    active
    notes
  }
}

mutation EDIT_BANK_BY_ID($id: ID!, $name:String!, $itno:String!, $account:String!, $active:Boolean, $notes:String) {
  editBankByID(updatedBank: {
    name : $name,
    itno : $itno,
    account : $account
    notes: $notes
    active : $active
  }, id: $id) {
    id
    name
    itno
    account
    active
    notes
  }
}

mutation DELETE_BANK_BY_ID($id: ID!){
  deleteBankById(id:$id){
    id
    message
    success
  }
}
