query GET_ALL_ROUTES {
  getAllRoutes {
    id
    name
    descriptions
    active
  }
}

query ROUTE_BY_ID($id: ID!) {
  getRouteById(id:$id) {
    id
    name
    descriptions
    active
  }
}

query ROUTE_BY_LIMIT_PAGE($page: Int!, $limit: Int!, $search: String) {
  getRoutesByLimitAndPage(
    page: $page,
    limit: $limit,
    search: $search
  ){
    routes{
      id,
      name,
      descriptions,
      active
    }
    paginator{
      currentPage,
      pageCount,
      prev,
      next,
      hasPrevPage
      hasNextPage
      perPage
      routeCount
    }
  }
}

mutation CREATE_NEW_ROUTE(
  $name: String!
  $descriptions: String!
  $active: Boolean
) {
  createNewRoute(
    newRoute: { 
        name: $name, 
        descriptions: $descriptions
        active: $active
    }
  ) {
    id
    name
    descriptions
    active
  }
}

mutation EDIT_ROUTE_BY_ID($id: ID!, $name:String!, $descriptions:String!, $active:Boolean) {
  editRouteByID(updatedRoute: {
    name : $name,
    descriptions : $descriptions,
    active : $active
  }, id: $id) {
    id
    name
    descriptions
    active
  }
}

mutation DELETE_ROUTE_BY_ID($id: ID!){
  deleteRouteById(id:$id){
    id
    message
    success
  }
}
